server:
  port: 5000
#  --------------------------------------------------------服务注册、发现------------------------------------------------------------------
eureka:
  client:
    serviceUrl:
        defaultZone: http://eureka00.cn:3000/eureka/,http://eureka01.cn:3001/eureka/,http://eureka03.cn:3003/eureka/  #eureka服务端提供的注册地址 参考服务端配置的这个路径
  instance:

    instance-id: user-0 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    # 每10秒发送一次心跳，超过30秒没有推动心跳，告知server，我已经挂掉了，可以清理
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

spring:
  application:
    name: client-user #此实例注册到eureka服务端的name

#  --------------------------------------------------------服务降级、熔断------------------------------------------------------------------
feign:
  hystrix:
    enabled: true #feign 默认是支持hystrix的， 但是在Spring - cloud Dalston 版本之后就默认关闭了

# （降级：仍会尝试调用服务，失败进入降级方法； 熔断：不会去尝试调用远程服务，直接进入降级方案,但默认会有5s的时间间隔尝试调用远程服务（半开状态），查看服务是否恢复）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  # 请求超时5秒，则进行降级 - 降级配置
      # 熔断配置
      circuitBreaker:
        requestVolumeThreshold: 5   # 一定时间内发生5次降级，自动熔断
#        sleepWindowInMilliseconds: 10000   # 上述指的 一定时间 ，默认10s 即 10s内5次服务请求异常，则发生熔断

